### ISSUE TITLE
Реализовать начисление баллов волонтёру за выполненное задание

### ISSUE THREAD

**Issue by kspshnik** [ya-pomogau/backend#103]
По ТЗ волонтёру должны начисляться баллы за каждое выполненное задание (и желательно сохранение количества выполненных заданий). В настоящее время такой функционал не реализован.

Необходимо провести рефакторинг схемы волонтёра и сервиса задач:

- [ ] Введение в схему волонтёра поля `tasksCompleted` типа `number`, со значением по умолчанию `0`;
- [ ] В сервисе задач необходимо создать **приватный** метод завершения заявки как выполненной, который будет:
   - Закрывать саму заявку как _успешно_ _выполненную_ (сейчас этот функционал продублирован в нескольких публичных методах сервиса);
   - Начислять (прибавлять к имеющимся) волонтёру баллы. Количество баллов определяется категорией выполненной задачи.
   - Увеличивать счётчик успешных задач у волонтёра на единицу.
- [ ] В сервисе  задач необходимо создать **приватный** метод  завершения заявки как *не выполненной*, **без начисления баллов и увеличения счётчика** (сейчас этот функционал продублирован в нескольких публичных методах сервиса).
- [ ] Перевести имеющиеся публичные методы на использование выше созданных приватных методов вместо прямого обращения к репозиториям.
- [ ] Проверить/протестировать правильность работы функционала, как добавленного так и имевшегося.

**Comment by IvannaBalanyuk** [comment]
Ссылка на PR: https://github.com/ya-pomogau/backend/pull/108
