### ISSUE TITLE
Добавить возможность массового редактирования категорий.

### ISSUE THREAD

**Issue by kspshnik** [ya-pomogau/backend#104]
Необходимо добавить в `AdminApiController` и `CategoriesService` контроллер ручки `@Patch('categorties')` и соответствующий метод в сервис, позволяющие осуществить редактирование одновременно нескольких категорий.
У Мангуста есть методы для массового обновления, например `bulkWrite()`.

- [ ] Создать интерфейс для dto.
- [ ] Создать dto, подготовить для работы `class-validator`.
- [ ] Написать ручку в `AdminApiController`.
- [ ] Создать метод в `CategoriesService`.
- [ ] Протестировать работу ручки и метода.

**Comment by IvannaBalanyuk** [comment]
Привет!
Ссылка на PR: https://github.com/ya-pomogau/backend/pull/109
