### ISSUE TITLE
Создание Websockets gateway для системных сообщений

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/backend#116]
Необходимо создать Websockets Gateway в  `SystemApi`.
На начальном этапе gateway должен поддерживать подключение пользователя.
Необходимо поддерживать и актуализовывать по факту происходящих событий соединения/отсоединения список подключённых клиентов для возможности отправки сообщения конкретному клиенту.

Должны быть реализованы все методы жизненного цикла:
![Image](https://github.com/user-attachments/assets/23eaae08-0625-47b3-b4e8-86d195fdf0da)

После подключения новому клиенту отправляется сообщение с полем `data` следующего формата:
```ts
data: { message: string, participants:  Array<string> }
// в поле message пишем 'Hello'
// в поле participants - массив всех текущих онлайн пользователей, _кроме_ текущего
```
, а всем остальным онлайн-клиентам: 
```ts
 data:  { message: 'Hello, world! <user.name> is online from now on!' }
```
При отключении всем пользователям отправляем 
```ts
{ message: 'Hello, world! <user.name> has dropped connection recently!' }
```

Необходимо поддерживать и актуализовывать по факту происходящих событий соединения/отсоединения список подключённых клиентов для возможности отправки сообщения конкретному клиенту.

Список литературы :) : 
[Официальная документация Nest.js (англ.)](https://docs.nestjs.com/websockets/gateways)
[Официальная документация Socket.io (англ.)](https://socket.io/)
[Поисковый запрос в YouTube](https://www.youtube.com/results?search_query=nest.js+websockets)
[Поисковый запрос на Хабре](https://habr.com/ru/search/?q=nest.js+websockets&target_type=posts&order=relevance)
И [Google](https://www.google.com) с [Яndex](https://www.yandex.ru) в помощь :)

**Comment by INextYP** [comment]
`feat/websockets-gateway`

**Comment by IvannaBalanyuk** [comment]
Ссылка на PR: [https://github.com/ya-pomogau/backend/pull/117](https://github.com/ya-pomogau/backend/pull/117)
