### ISSUE TITLE
Добавление гарды и логики авторизации сокета

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/backend#119]
В рамках задачи необходимо добавить дополнительный `Guard` по пути `src/common/guards`.
- [ ] Назвать файл - `socket-auth.guard.ts`

Гвард должен:
- [ ] Наследоваться от `CanActivate` (`implements CanActivate`)
- [ ] Внедрять в конструкторе `JwtService`
- [ ] В методе `canActivate` проверять наличие токена, а также верифицировать его с помощью
`jwtService.verify` метода
- [ ] Токен при подключении нужно указывать в `headers.authorization`
- [ ] Если токен невалиден, то нужно выбрасывать `WsException`

`handleConnection` метод должен видоизмениться:
- [ ] Теперь мы не передаём query при подключении, а проверяем токен пользователя и забираем объект пользователя из токена (пока просто выводить в консоль верифицированного пользователя), т.е.:
```
// 1. Проверяем токен (в случае, если он невалиден, то выбрасываем WsException)
// 2. Из полученного выше `payload` получаем объект пользователя
// 3. Выводим в консоль пользователя
```
- [ ] в handleConnection поменять везде, где у нас использовались данные пользователя из query на те, что у нас приходит из объекта выше

**Comment by INextYP** [comment]
`feat/auth-socket-guard`

**Comment by kspshnik** [comment]
Соответственно в нашу `Map` внутри gateway записываем по ключу id соединения объект пользователя из payload ;o)

**Comment by IvannaBalanyuk** [comment]
Создала PR) Вот ссылка https://github.com/ya-pomogau/backend/pull/129
