### ISSUE TITLE
Изменение `permissions`  у админа

### ISSUE THREAD

**Issue by Anton-Laid** [ya-pomogau/backend#131]
На данный момент есть две ручки

- http://localhost:3001/admin/{id}/privileges 
- http://localhost:3001/admin/{id}/privileges

Нужно объединить функционал их в одной
Сейчас одна ручка добавляет функционал админу, другая их удаляет
![Снимок 25 07 2024 в 20 49](https://github.com/user-attachments/assets/cfed64ed-f17b-4f74-bbcf-39cb50316b59)
На фронте для всего только одна кнопка( 

Нужна чтобы ручка могла получать массив разной наполненности или пустой и просто переписывала у админа в `permissions` 

- [ ] Создание ручки в `AdminApiController`. Ручка должна по url (':id/privileges') обрабатывать PATCH-запрос, сигнатура должна совпадать с сигнатурой ручек PUT и DELETE по тому же url (уже есть в контроллере). Декорируется `AccessControlList` аналогично имеющимся ручкам. Dto используем то же такую же.
- [ ] Создание метода в `UsersService`. Публичный метод вызывается из контроллера (`AdminApiController`), обращается к репозиторию пользователей, и заменяет массив привилегий у администратора.

**Comment by IvannaBalanyuk** [comment]
@kspshnik, ветка feature/patch-admin-privileges (?) =)

**Comment by kspshnik** [comment]
> @kspshnik, ветка `feature/patch-admin-privileges` (?) =)

@IvannaBalanyuk, ага :)
![2024-07-26_11-57-54](https://github.com/user-attachments/assets/1d2ef69c-ee01-4af2-9bcc-4809c6782731)

**Comment by IvannaBalanyuk** [comment]
> ага :)

Упс... А слона то я и не заметила)) Спасибо)

**Comment by IvannaBalanyuk** [comment]
Ссылка на PR: https://github.com/ya-pomogau/backend/pull/134
