### ISSUE TITLE
Проверка auth-api.controller

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/backend#148]
Ветка не требуется.

В рамках задачи необходимо:

- [ ] Проверить все ручки на наличие валидации DTO, Query, Params
- [ ] Проверить корректное отображение и описание ручек для Swagger
- [ ] Проверка наличия ручек в постман коллекции (в корне репозитория) с примерами запросов

По задаче выполняется только проверка пунктов выше. После полной проверки, в зависимости от объема ошибок, будут сформированы задачи на исправления.

Итог выполнения задачи - комментарий к этой карточке в формате чек-листа:
такая-то ручка:
- [ ] валидация ОК/ не ОК
- [ ] Сваггер ОК/ не ОК
- [ ] Постман коллекция ОК/ не ОК

**Comment by TerSV86** [comment]
Для всех ДТО в декоратор @ApiProperty добавить описание поля description и example (для автоматического заполнения полей в свагере).
В контроллере добавить тег (ApiTags), описать структуру ответа (ApiResponse) и ответы в виде ошибок (ApiUnauthorizedResponse) для сваггера.
В main для SwaggerModule добавить параметр swaggerOptions: { persistAuthorization: true }
1.  /auth/vk :
- [ ] валидация - добавить проверку redirectUrl для того, чтобы убедиться, что это HTTP-адрес
- [ ] сваггер - выдает ошибку 401, из-за запроса access_token на oauth.vk
- [ ] постман коллекция 

2.  /auth/new
- [x] валидация
- [ ] сваггер - отсутствует структура PointGeoJSONDto
- [ ] постман коллекция 

3. /auth/administrative
- [ ] валидация - отсутствует проверка тела запроса {"login": "string","password":"string"}
- [ ] сваггер не описаны параметры, ошибки, ответ
- [x] постман коллекция 

4. /auth/mock
- [ ] валидация - mockLoginDto описан в файле auth-api.controller.ts (реализовать в директории dto по аналогии с  VkLoginDto, VKNewUserDto)
- [ ] сваггер - отсутствует описание mockLoginDto
- [ ] постман коллекция 

5. /auth/token
- [x] валидация
- [ ] сваггер - не описаны параметры, ошибки, ответ
- [ ] постман коллекция
