### ISSUE TITLE
Проверка admin-api.controller

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/backend#149]
Ветка не требуется.

В рамках задачи необходимо:

- [ ] Проверить все ручки на наличие валидации DTO, Query, Params
- [ ] Проверить корректное отображение и описание ручек для Swagger
- [ ] Проверка наличия ручек в постман коллекции (в корне репозитория) с примерами запросов

По задаче выполняется только проверка пунктов выше. После полной проверки, в зависимости от объема ошибок, будут сформированы задачи на исправления.

Итог выполнения задачи - комментарий к этой карточке в формате чек-листа:
такая-то ручка:
- [ ] валидация ОК/ не ОК
- [ ] Сваггер ОК/ не ОК
- [ ] Постман коллекция ОК/ не ОК

**Comment by AlexeyKrutyakov** [comment]
- [ ] Проверить все ручки на наличие валидации DTO, Query, Params
- [ ] Проверить корректное отображение и описание ручек для Swagger
- [ ] Проверка наличия ручек в постман коллекции (в корне репозитория) с примерами запросов
- нет ручек, кроме `admin/create` и `auth/administrative`

**Comment by AlexeyKrutyakov** [comment]
с Query не разобрался, нужна помощь, видимо в discord

**Comment by AlexeyKrutyakov** [comment]
admin/ all
- [x] Валидация не требуется
- [x] Swagger - OK
- [ ] Postman - не OK

admin/create
- [x] Валидация (DTO) - ОК
- [x] Swagger - OK
- [x] Postman - OK

admin/:id/activate (PUT)
- [ ] Валидация (Param) - не ОК (id: string)
- [x] Swagger - OK
- [ ] Postman - не OK

admin/:id/activate (DELETE)
- [ ] Валидация (Param) - не ОК (id: string)
- [x] Swagger - OK
- [ ] Postman - не OK

admin/:id/priveleges (PUT)
- [ ] Валидация (Param) - не ОК (id: any), (DTO) - OK
- [x] Swagger - OK
- [ ] Postman - не OK

admin/:id/priveleges (DELETE)
- [ ] Валидация (Param) - не ОК (id: any), (DTO) - OK
- [x] Swagger - OK
- [ ] Postman - не OK

admin/:id/priveleges (PATCH)
- [ ] Валидация (Param) - не ОК (id: any), (DTO) - OK
- [x] Swagger - OK
- [ ] Postman - не OK

admin/users/:id/confirm (PUT)
- [ ] Валидация (Param) - не ОК (id: string)
- [x] Swagger - OK
- [ ] Postman - не OK

admin/users/:id/confirm (DELETE)
- [ ] Валидация (Param) - не ОК (id: string)
- [x] Swagger - OK
- [ ] Postman - не OK

admin/users/:id/promote (PUT)
- [ ] Валидация (Param) - не ОК (id: string)
- [x] Swagger - OK
- [ ] Postman - не OK

admin/users/:id/promote (DELETE)
- [ ] Валидация (Param) - не ОК (id: string)
- [x] Swagger - OK
- [ ] Postman - не OK

admin/users/:id/keys (PUT)
- [ ] Валидация (Param) - не ОК (id: string)
- [x] Swagger - OK
- [ ] Postman - не OK

admin/users/:id/keys (DELETE)
- [ ] Валидация (Param) - не ОК (id: string)
- [x] Swagger - OK
- [ ] Postman - не OK

admin/blog
- [x] Валидация (DTO) -ОК
- [x] Swagger - OK
- [ ] Postman - не OK

admin/blog/:id (PATCH)
- [ ] Валидация (Param) - не ОК (id: string), (DTO) - OK
- [x] Swagger - OK
- [ ] Postman - не OK

admin/blog/:id (DELETE)
- [ ] Валидация (Param) - не ОК (id: string)
- [x] Swagger - OK
- [ ] Postman - не OK

admin/category
- [x] Валидация (DTO) - OK
- [x] Swagger - OK
- [ ] Postman - не OK

admin/categories
- [x] Валидация (DTO) - OK
- [x] Swagger - OK
- [ ] Postman - не OK

admin/categories/:id (PATCH)
- [ ] Валидация (Param) - не ОК (id: string), (DTO) - OK
- [x] Swagger - OK
- [ ] Postman - не OK

admin/categories/:id (DELETE)
- [ ] Валидация (Param) - не ОК (id: string)
- [x] Swagger - OK
- [ ] Postman - не OK

admin/tasks/conflicted
- [x] Валидация не требуется
- [x] Swagger - OK
- [ ] Postman - не OK

admin/users/volunteers
- [x] Валидация не требуется
- [x] Swagger - OK
- [ ] Postman - не OK

admin/users/recipients
- [x] Валидация не требуется
- [x] Swagger - OK
- [ ] Postman - не OK

admin/users/unconfirmed
- [x] Валидация не требуется
- [x] Swagger - OK
- [ ] Postman - не OK

admin/tasks/:id/resolve
- [ ] Валидация (Param) - не ОК (id: string)
- [x] Swagger - OK
- [ ] Postman - не OK

admin/tasks/:id/resolve/fulfill
- [ ] Валидация (Param) - не ОК (id: string)
- [x] Swagger - OK
- [ ] Postman - не OK

admin/tasks/:id/resolve/reject
- [ ] Валидация (Param) - не ОК (id: string)
- [x] Swagger - OK
- [ ] Postman - не OK

admin/tasks/moderated
- [x] Валидация не требуется
- [x] Swagger - OK
- [ ] Postman - не OK

admin/contacts
- [x] Валидация (DTO) - OK
- [x] Swagger - OK
- [ ] Postman - не OK
