### ISSUE TITLE
Проверка recipient-api.controller

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/backend#150]
Ветка не требуется.

В рамках задачи необходимо:

- [x] Проверить все ручки на наличие валидации DTO, Query, Params
- [x] Проверить корректное отображение и описание ручек для Swagger
- [x] Проверка наличия ручек в постман коллекции (в корне репозитория) с примерами запросов

По задаче выполняется только проверка пунктов выше. После полной проверки, в зависимости от объема ошибок, будут сформированы задачи на исправления.

Итог выполнения задачи - комментарий к этой карточке в формате чек-листа:
такая-то ручка:
- [x] валидация ОК/ не ОК
- [x] Сваггер ОК/ не ОК
- [x] Постман коллекция ОК/ не ОК

**Comment by IvannaBalanyuk** [comment]
**Post('/tasks'):**
- [x]  Валидация: `ОК` (DTO).
- [x]  Swagger: в целом `ОК`, но стоит добавить опцию `example` в `@ApiProperty` - `@ApiProperty({ example: 'ab0381c3-57cd-45c0-97bd-fbd50fd996c5' })`. В случае с `location`, например, сейчас не видно, что ожидается массив из двух элементов.
- [ ]  Постман коллекция: `не ОК` (ручка отсутствует в коллекции).

---

**Get('/tasks/virgin'):**
- [x]  Валидация: `ОК` (Query).
- [x]  Swagger: `ОК`.
- [ ]  Постман коллекция: `не ОК` (ручка отсутствует в коллекции).

**Примечание:** в методе сервиса `getTasksByStatus` из dto получаем `location`, но в контроллере dto типизирован `GetTasksQueryDto`, в котором `location` нет. Похоже в ручке не хватает такого фрагмента:

![Image](https://github.com/user-attachments/assets/b1da670a-b8d2-4cda-be21-7d996ccf90f0)

---

**Put('/tasks/:id/fulfill')**
- [x]  Валидация: `ОК` (Param).
- [x]  Swagger: `ОК`.
- [ ]  Постман коллекция: `не ОК` (ручка отсутствует в коллекции).

**Примечание:** в контроллере получаем юзера (`@Req() { user: { _id: userId }`), передаем `userId` в метод `reportTask` сервиса, но в самом методе `userId` не использован:
![Image](https://github.com/user-attachments/assets/77e66f08-7de0-499b-b322-fd4b98aaf0b7)

---

**Put('/tasks/:id/reject')**
- [x]  Валидация: `ОК` (Param).
- [x]  Swagger: `ОК`.
- [ ]  Постман коллекция: `не ОК` (ручка отсутствует в коллекции).

**Примечание:** в контроллере получаем юзера (`@Req() { user: { _id: userId }`), передаем `userId` в метод `reportTask` сервиса, но в самом методе `userId` не использован (см. скрин в предыдущей ручке).

---

**Get('/tasks/accepted')**
- [x]  Валидация: `ОК` (Query).
- [x]  Swagger: `ОК`.
- [ ]  Постман коллекция: `не ОК` (ручка отсутствует в коллекции).

---

**Get('/tasks/active')**
- [x]  Валидация: `ОК` (Query).
- [x]  Swagger: `ОК`.
- [ ]  Постман коллекция: `не ОК` (ручка отсутствует в коллекции).

---

**Get('/tasks/completed')**
- [x]  Валидация: `ОК` (Query).
- [x]  Swagger: `ОК`.
- [ ]  Постман коллекция: `не ОК` (ручка отсутствует в коллекции).

---

**Get('/tasks/:id')**
- [x]  Валидация: `ОК` (Param).
- [x]  Swagger: `ОК`.
- [ ]  Постман коллекция: `не ОК` (ручка отсутствует в коллекции).

---

**Patch('/tasks/:id')**
- [x]  Валидация: `ОК` (Param, Body).
- [x]  Swagger: в целом `ОК`, но стоит добавить опцию `example` в `@ApiProperty` - `@ApiProperty({ example: 'ab0381c3-57cd-45c0-97bd-fbd50fd996c5' })`.
- [ ]  Постман коллекция: `не ОК` (ручка отсутствует в коллекции).

---

**Delete('/tasks/:id')**
- [x]  Валидация: `ОК` (Param).
- [x]  Swagger: `ОК`.
- [ ]  Постман коллекция: `не ОК` (ручка отсутствует в коллекции).

---

**Примечание общее:** применены разные подходы к типизации запроса:
- типизируем запрос целиком (`@Req() req: Express.Request`) и нужные данные извлекаются уже в теле метода;
- сразу деструктурируем и забираем данные (`@Req() { user }`), которые потом в теле метода типизируем;
- тоже сразу деструктурируем и забираем данные (`@Req() { user: { _id: userId } }`), но и в теле метода НЕ типизируем.
Нужно ли привести к одному варианту и если да, то какой предпочтительнее?

**Comment by kspshnik** [comment]
Отлично!!!
