### ISSUE TITLE
Проверка system-api.controller

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/backend#151]
Ветка не требуется.

В рамках задачи необходимо:

- [ ] Проверить все ручки на наличие валидации DTO, Query, Params
- [ ] Проверить корректное отображение и описание ручек для Swagger
- [ ] Проверка наличия ручек в постман коллекции (в корне репозитория) с примерами запросов

По задаче выполняется только проверка пунктов выше. После полной проверки, в зависимости от объема ошибок, будут сформированы задачи на исправления.

Итог выполнения задачи - комментарий к этой карточке в формате чек-листа:
такая-то ручка:
- [ ] валидация ОК/ не ОК
- [ ] Сваггер ОК/ не ОК
- [ ] Постман коллекция ОК/ не ОК

**Comment by TerSV86** [comment]
В @ApiProperty добавить описание поля description и example (для автоматического заполнения полей в свагере).
1 posts
- [x]  валидация 
- [x] Сваггер
- [x] Постман коллекция 

2 posts/:id
- [ ]  валидация -  отсутствует валидация Param('id').  Создать IdParamDto и описать id как IsMongoId.  
- [ ] Сваггер  
- [x] Постман коллекция 

3 categories
- [x]  валидация  
- [x] Сваггер
- [ ] Постман коллекция 

4 categories/:id
- [ ]  валидация  -  отсутствует валидация Param('id').  Создать IdParamDto и описать id как IsMongoId. 
- [ ] Сваггер
- [ ] Постман коллекция

5 tasks/virgin
- [x]  валидация - В GetTasksQueryDto categoryId описать как  IsMongoId
- [x] Сваггер
- [ ] Постман коллекция

6 (GET) profile 
- [x]  валидация  
- [x] Сваггер
- [ ] Постман коллекция

7 (PATCH) profile
- [x]  валидация 
- [ ] Сваггер - не описаны параметры
- [ ] Постман коллекция 

8 contacts
- [x]  валидация 
- [x] Сваггер
- [ ] Постман коллекция 

9 policy
- [x]  валидация 
- [x] Сваггер
- [ ] Постман коллекция
