### ISSUE TITLE
Проверка volunteer-api

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/backend#152]
Ветка не требуется.

В рамках задачи необходимо:

- [ ] Проверить все ручки на наличие валидации DTO, Query, Params
- [ ] Проверить корректное отображение и описание ручек для Swagger
- [ ] Проверка наличия ручек в постман коллекции (в корне репозитория) с примерами запросов

По задаче выполняется только проверка пунктов выше. После полной проверки, в зависимости от объема ошибок, будут сформированы задачи на исправления.

Итог выполнения задачи - комментарий к этой карточке в формате чек-листа:
такая-то ручка:
- [ ] валидация ОК/ не ОК
- [ ] Сваггер ОК/ не ОК
- [ ] Постман коллекция ОК/ не ОК

**Comment by AlexeyKrutyakov** [comment]
Примечание: в VolunteerApiController не используется приватное поле userService

volunteer/tasks/virgin
- [x] Валидация (Query) - ОК
- [x] Swagger - OK
- [ ] Postman - не OK

volunteer/tasks/:id/accept
- [ ] Валидация (Param) - не ОК
- [x] Swagger - OK
- [ ] Postman - не OK

volunteer/tasks/:id/fulfill
- [ ] Валидация (Param) - не ОК
- [x] Swagger - OK
- [ ] Postman - не OK

volunteer/tasks/:id/reject
- [ ] Валидация (Param) - не ОК
- [x] Swagger - OK
- [ ] Postman - не OK

volunteer/tasks/accepted
- [x] Валидация (Query) - ОК
- [x] Swagger - OK
- [ ] Postman - не OK

volunteer/tasks/completed
- [x] Валидация (Query) - ОК
- [x] Swagger - OK
- [ ] Postman - не OK
