### ISSUE TITLE
Добавление AdminApi в Postman коллекцию

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/backend#163]
Ветка для работы - `feat/add-admin_api-postman-collection`

В корне репозитория бекенда есть файлик `postman_collection.json` в котором находятся определенный список ручек.

В рамках задачи необходимо взять этот файл, открыть в постмане и добавить все ручки из `src/api/admin-api/admin-api.controller.ts` с примером запроса.

В пулл-реквест должен  попасть `postman_collection.json` со всеми ручками выше. Желательно в постмане сгруппировать ручки в одну папку.

Обязательно проверь, что любой запрос можно совершить просто выбрав нужную ручку (руками токен вбивать - такое себе)

**Comment by norv139** [comment]
https://github.com/ya-pomogau/backend/pull/171
