### ISSUE TITLE
Вынос gateway сокета в отдельный Api

### ISSUE THREAD

**Issue by IvannaBalanyuk** [ya-pomogau/backend#175]
Ветка для работы - `refactor/move-websocket-gateway`

Задача: вынести ранее созданный WebSocket gateway (`SystemApiGateway`) из `SystemApi` в отдельный api - `WebsocketApi`.

В рамках задачи нужно сделать следующее:
- [x] создать папку `websocket-api` в `src/api`, добавить файлы `websocket-api.gateway.ts` и `websocket-api.module.ts`;
- [x] перенести код `SystemApiGateway` в `websocket-api.gateway.ts` (класс переименовать);
- [x] создать `WebsocketApiModule` в `websocket-api.module.ts`, добавить все необходимые импорты;
- [x] удалить файл с SystemApiGateway из `SystemApi`, убрать `SystemApiGateway` из `SystemApiModule`;
- [x] внести изменения в `SendTokenHandler` и в `UsersModule` (в части импортов и имени gateway);
- [x] проверить в Postman сохранена ли работоспособность сокета.

О том, как работать с сокет-соединением в Postman, можно почитать тут:
[Постман, работа с Socket.io](https://blog.postman.com/postman-now-supports-socket-io/)

Для общего ознакомления с тем, что такое WebSockets и socket.io в контексте Nest.js, можно почитать/посмотреть тут: 
[Официальная документация Nest.js (англ.)](https://docs.nestjs.com/websockets/gateways)
[Официальная документация Socket.io (англ.)](https://socket.io/)
[Поисковый запрос в YouTube](https://www.youtube.com/results?search_query=nest.js+websockets)
[Поисковый запрос на Хабре](https://habr.com/ru/search/?q=nest.js+websockets&target_type=posts&order=relevance)
Ну и [Google](https://www.google.com) с [Яndex](https://www.yandex.ru) в помощь :)

**Comment by kspshnik** [comment]
А в какой ветке-то ты делала? @Sapodsoblyaeva?

**Comment by kspshnik** [comment]
Закрыто с PR #187
