### ISSUE TITLE
Бэкенд. Логирование поступающих запросов

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/backend#181]
Нужно написать Logger Middleware, который все поступающие запросы в консоль будет писать с помощью **Logger** от **@nestjs/common билиотеки**

Этот Middleware будет подключаться в **AppModule** 

Вывод должен быть примерно такой method url statusCode

Пример вывода в консоль:
```
LOG [HTTP] POST /auth/administrative 401
```

**Comment by INextYP** [comment]
ветка для работы - `feat/add-logger-middleware `

**Comment by norv139** [comment]
https://github.com/ya-pomogau/backend/pull/186
