### ISSUE TITLE
Исправление ошибок типизации в схемах чатов

### ISSUE THREAD

**Issue by kspshnik** [ya-pomogau/backend#191]
Сейчас приложение не собирается, т.к. конфликтуют (несовместимы) типы в интерфейсе и схемах конфликтных чатов реципиента и волонтёра, чата таски и сообщения.

Необходимо привести типы к общему знаменателю.

**Comment by Varikash** [comment]
https://prnt.sc/LXWnhrzsqNjO - файлы в которые я внес изменения чтобы собрать проект.

Импорт должен быть таким:

`import { Types, Document, SchemaTypes } from 'mongoose';`

А дальше вместо ObjectId пишешь Types.ObjectId;

**Comment by im-Arn** [comment]
@zoomkolol изменение импорта в файлах chat.types.ts фиксит ошибки, переделай на с mongodb на mongoose.
т.е. 
`import { type ObjectId } from 'mongodb';`
на
`import { type ObjectId } from 'mongoose';`
и больше никаких изменений нигде не требуется. 
аналогично ко всем конфликтам

**Comment by Varikash** [comment]
> [@zoomkolol](https://github.com/zoomkolol) изменение импорта в файлах chat.types.ts фиксит ошибки, переделай на с mongodb на mongoose. т.е. `import { type ObjectId } from 'mongodb';` на `import { type ObjectId } from 'mongoose';` и больше никаких изменений нигде не требуется. аналогично ко всем конфликтам

Это решение даже изящней.

**Comment by kspshnik** [comment]
@zoomkolol @Varikash @im-Arn Можно и так, и так. Главное, чтобы подход был **единообразный**.

**Comment by zoomkolol** [comment]
Эта проблема вылезла как раз из-за того, когда я делал моковый сервис чата. Сейчас верну обратно здесь mongoose, но @kspshnik нужно делать новый issue на фикс мокового сервиса чатов (у него будут ошибки опять, буду сидеть думать как исправить).

**Comment by kspshnik** [comment]
> Эта проблема вылезла как раз из-за того, когда я делал моковый сервис чата. Сейчас верну обратно здесь mongoose, но @kspshnik нужно делать новый issue на фикс мокового сервиса чатов (у него будут ошибки опять, буду сидеть думать как исправить).


Не, надо сделать так, чтобы **везде** работало.
