### ISSUE TITLE
SystemApi

### ISSUE THREAD

**Issue by kspshnik** [ya-pomogau/backend#66]
Создать `SystemApiController` по роуту `/system`.

- [x] Создание контроллера и модуля - @margo-yunanova.
- [x] Создание ручки получения списка категорий (GET `/categoties`) - @ulbee.
- [x] Создание ручки получения отдельной категории (GET `/categoties/:id`)  - @ulbee.
- [x] Создание ручки получения постов из блога (`GET /posts`) - @margo-yunanova.
- [x] Создание ручки получения отдельного поста из блога (`GET /posts/:id`) - @margo-yunanova.
- [x] Создание ручки получения задач для неавторизованного пользователя (с `TaskStatus.CREATED`) (GET '/active-tasks')  - @ulbee.
- [x] Создание ручки получения текущей политики ПД (GET '/policy')  - @ulbee.
- [ ] Создание ручки получения текущих контактов (GET `/contacts`)  - @ulbee.
- [ ] Создание ответа 405 на все остальные запросы и методы ('new MethodNotAllowedException()`)  - @ulbee.

**Comment by margo-yunanova** [comment]
@kspshnik , ты что-то делаешь по этой задаче? Давай я для начала сделаю модуль и закину свои блог апи?

**Comment by kspshnik** [comment]
> @kspshnik , ты что-то делаешь по этой задаче? Давай я для начала сделаю модуль и закину свои блог апи?

О! Спасибо, @margo-yunanova, это будет супер :)
Фичеветка уже есть - [`feature/system-api`](https://github.com/ya-pomogau/backend/tree/feature/system-api), от неё отстройся и делай, PR в неё же.

**Comment by ulbee** [comment]
@kspshnik Женя, подскажи, как должен выглядеть ответ в последнем пункте issue? Подойдет такой
`{
        status,
        message,
        method,
        url,
  }`?

Я хочу сделать фильтром - только для SystemApiController подключить или глобально?

**Comment by kspshnik** [comment]
> Я хочу сделать фильтром - только для SystemApiController подключить или глобально?

Смотри, наше дело - кинуть исключение, а преобразует его уже сам Nest.
