### ISSUE TITLE
Создание ручек для CUD категорий в  `/admin`

### ISSUE THREAD

**Issue by kspshnik** [ya-pomogau/backend#69]
(АКТУАЛЬНО ПОСЛЕ ВЛИВАНИЯ PR ПО СЕРВИСУ КАТЕГОРИЙ)

Создать в `AdminApiController` ручки для работы с категориями (кроме получения):

- [x] Создание категории (POST `/categories`)
- [x] Редактирование конкретной категории (PATCH `/categories/:id`)
- [x] Удаление конкретной категории (DELETE `/categories/:id`

**Comment by kspshnik** [comment]
В рамках починки флоу задач - добавил ручку на создание категории в `AdminApi`, без неё не протестировать было создание задачи.

**Comment by ulbee** [comment]
https://github.com/ya-pomogau/backend/pull/79
