### ISSUE TITLE
Проверить создание заявки

### ISSUE THREAD

**Issue by AlexandrGerasimov63** [ya-pomogau/backend#77]
- [x] При передаче "date":null 
![image](https://github.com/ya-pomogau/backend/assets/97280804/e53d6ccf-52d3-4327-a906-1d9cc6aadafb)
![image](https://github.com/ya-pomogau/backend/assets/97280804/75af6508-982e-408a-9125-02584f9b4239)

- [x] При передаче "date": "2024-02-13T16:45:00Z"
![image](https://github.com/ya-pomogau/backend/assets/97280804/027dfd87-c401-48ba-b51b-52df549a7371)

**Comment by INextYP** [comment]
@kspshnik ^)
1. В `ApiCreateTaskDto` нужно поменять `@IsDate()` на `@IsDateString()`.
2. Зачем в схеме таски `_id`? Из-за неё валится ошибка - Task validation failed: _id: Path `_id` is required.
3. Сочетание в @Prop-декораторе ключей `default` (со значение `null`) и `enum` выбивают 500-ю ошибку ( `null` is not a valid enum value for path). Помогает исключение `default `из обьекта декоратора у `adminResolve`, `volunteerReport`, `recipientReport`
4. В схеме таски `volunteer` может быть `null` и необязательным, т.е. 

```
@Prop({ type: raw(rawUserProfile), immutable: true, default: null })
  volunteer: UserProfile | null;
```
5. В схеме таски `date` нужно убрать `required: true` и добавить дефолтное значение `null`
6. В схеме таски `location` у тебя объект, а при создании таски передается массив. Чтобы исправить (предлагаю решение "В лоб"), нужно в методе `create`  в `taskService` указывать `location: {type: 'Point', coordinates: location}` в обьекте `task`.

Вот после исправления этих 6-ти пунктов таска с передаваемым телом выше создалась.

**Comment by kspshnik** [comment]
> 3. Сочетание в @Prop-декораторе ключей `default` (со значение `null`) и `enum` выбивают 500-ю ошибку ( `null` is not a valid enum value for path). Помогает исключение `default `из обьекта декоратора у `adminResolve`, `volunteerReport`, `recipientReport`

А вот так: `enum: [...Object.values<string>(TaskReport), null],` - не получится?

**Comment by kspshnik** [comment]
> @kspshnik ^)
Да-да? :)

Короче, @INextYP , всё починил. 1, 2, 4, 6 - по твоему рецепту, а 3 и 5 - смотри сам:

```ts
  @Prop({
    default: null,
    type: mongoose.SchemaTypes.String,
    enum: [...Object.values<string>(ResolveStatus), null],
    required: false,
  })
  adminResolve: ResolveStatus | null;

```

и аналогично с обоими отчётами.

```ts
  @Prop({ required: false, type: mongoose.SchemaTypes.Date })
  date: Date | null;

```

Оказывается, прямое указание. `required: false` в объекте `mongoose.schemaOptions` разрешает `null`. Но если используется `enum` - надо в лоб включить его в перечисление.

В ветку под [PR #72](https://github.com/ya-pomogau/backend/pull/72) коммит с исправлениями запушил. Можешь смотреть :)

P.S. Таска создалась :) /kspshnik
