### ISSUE TITLE
Планирование модели данных для чата

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/backend#95]
В рамках задачи нужно сформировать: 
- ER-диаграмму, представляющую модель данных;
- Документацию, описывающую сущности модели данных (какое поле за что отвечает)

Итоговый формат утвердим на QA и на следующем спринте можно будет сформировать задачу на реализацию

**Comment by kspshnik** [comment]
RFC enclosed ;o)

![Chat Entity data model proposal](https://github.com/ya-pomogau/backend/assets/11374004/add9483d-4953-47b6-9bbf-0f4de919a3ad)

**Comment by FenixDeveloper** [comment]
Делаем две коллекции: для сообщений и для чатов

**Comment by kspshnik** [comment]
Модель данных определена.
