### ISSUE TITLE
Создание репозитория чатов по модели данных

### ISSUE THREAD

**Issue by kspshnik** [ya-pomogau/backend#97]
Необходимо описать типизацию и создать репозиторий чатов по модели данных. 
Коллекция дискриминированная, ключ дискриминатора - поле `kind`.
Создание такого репозитория делаем по аналогии с `src/datalake/users`.

Типизация *discriminator key*:
```ts
export const ChatType = {
    Task: 'TASK_CHAT',
    System: 'SYSTEM_CHAT' ,
    ConflictVolunteer: 'CONFLICT_CHAT_VOLUNTEER',
    ConflictRecipient: 'CONFLICT_CHAT_RECIPIENT',
} as const;

export type ChatType = keyof typeof ChatType;
```
- [ ] Создать интерфейсы для коллекции по модели данных в `src/common/types/chats.ts`
- [ ] Создать модуль репозитория для коллекции чатов в слое данных (`/src/datalake`) по аналогии с `UsersRepositoryModule`
- [ ] Создать сервис репозитория для коллекции чатов с использованием `BaseRepositoryService`, по аналогии с `UsersRepository`.

Статические методы *пока* **не реализуем*.

Модель данных:
![2024-06-06_22-07-32](https://github.com/ya-pomogau/backend/assets/11374004/e9ff6424-f093-49d2-83c2-693ed2473b9c)

**Comment by AlexeyKrutyakov** [comment]
@kspshnik привет!
в какой ветке работать?

**Comment by AlexeyKrutyakov** [comment]
@kspshnik , @INextYP всё сделал, статические методы пока не трогал

оатались вопросы:

1. В схемах чатов оставил возможности применять кастомные геттеры и преобразованием полей с ObjectId в строку - правильно?
2. Нужно ли удалить дублирующиеся сущности из папок datalake и common/types под названием chat.ts - это отдельная таска? обозначаю, что они только путают сейчас разрабов, которые не знакомы с проектом
3. пока не применял `raw` в типах `@Prop`, как это сделано для `datalake/blog-post` - если честно, до конца не понял, как это сделать.

ссылка на pull-request в карточке, нужно в сообщении дублировать?
