### ISSUE TITLE
Ручка для редактирования контактов на бэкенде

### ISSUE THREAD

**Issue by kspshnik** [ya-pomogau/backend#99]
Необходимо создать ручку для редактирования (изменения) контактов на бэкенде в `SystemApiController`: `PATCH system/contacts`, и создать соответствующий dto в `src/common/dto`.

- [ ] UpdateContactsRequestDto
- [ ] updateContacts() method.

**Comment by IvannaBalanyuk** [comment]
Привет!
Ссылка на PR: https://github.com/ya-pomogau/backend/pull/100
